Replace reference to html40 by html401
This fixes a fatal error reported by bikeshed during make:

FATAL ERROR: Obsolete biblio ref: [html40] is replaced by [HTML401].

Possible regression from 719238c9f1ae64316ba31c51dffc2eedf4a99423